### ISSUE TITLE
Top Level Mono-repository File Throws Error

### ISSUE THREAD

**Issue by hbetts** [factset/deprecator#32]
Mono-repository projects, in particular JavaScript mono-repositories, tend to have a top-level `package.json` file that contains development dependencies used by all packages in the mono-repository. The top level `package.json` file is not intended to be published to a package repository. 

When `deprecator` fetches the top level `package.json` file, it will automatically attempt to query a package repository for metadata about the package described in the `package.json` file using the name listed in the `name` property.

However, because the package isn't published, the query will always fail.

In a worker process it looks like this:

```bash
deprecator failed to fetch package, [PACKAGE NAME], metadata from the registry - 404 - Not Found { error: 'Not found' }
[worker-1] HTTPError: Response code 404 (Not Found)
  at stream.catch.then.data (/app/node_modules/got/index.js:372:13)
  at process._tickCallback (internal/process/next_tick.js:68:7) 
```

i would like to see us gracefully handle these errors. It may not be possible to completely ignore them since it's impossible to know, for certain, that the top-level `package.json` file is not published (except in the case where it's marked `private`)

**Comment by hbetts** [comment]
We can begin with ignore private packages as discussed in #33
